global:
  resolve_timeout: 1m

route:
  receiver: lab28-webhook
  group_by: [alertname, job]
  group_wait: 5s
  group_interval: 30s
  repeat_interval: 4h

receivers:
  - name: lab28-webhook
    webhook_configs:
      - url: http://alert-receiver:8080/alerts
        send_resolved: true
